---
# サーバメンテナンス、ドキュメント所有者

 #鍵認証の為PWは設定しない
 - name: ユーザ追加
   user:
     name: "{{ apache_user }}"
     state: present

 - name: make authorized key directory
   file:
      path: /home/{{ apache_user }}/.ssh
      state: directory
      owner: "{{ apache_user }}"
      group: "{{ apache_user }}"
      mode: 0700

 - name: add authorized key
   copy:
     src: "ssh/{{ apache_user }}_id_rsa.pub"
     dest: "/home/{{ apache_user }}/.ssh/authorized_keys"
     mode: 0600
     owner: "{{ apache_user }}"
     group: "{{ apache_user }}"
     
 - name: make public directory
   file:
     path: "/home/{{ apache_user }}/www/html"
     state: directory
     owner: "{{ apache_user }}"
     group: "{{ apache_user }}"



