---
# These tasks install http and the php modules.

 - name: Install http and php etc
   yum: name={{ item }} state=installed
   with_items:
    - httpd
    - php
    - php-gd
    - php-mysql
    - php-mbstring
    - php-xml
    - php-mcrypt
    - mod_ssl
    - python-setuptools
   notify:
     - "start and enable apache on boot"
     
 - name: Install mod_ruid2
   yum: name=mod_ruid2 state=installed enablerepo=epel
   notify:
     - "start and enable apache on boot"
     
 - pip: name=passlib
